metadata:
  kind: MainConfig
  cluster: ydb-cluster
  version: 0
config:
  erasure: none
  fail_domain_type: disk
  default_disk_type: SSD
  yaml_config_enabled: true

  actor_system_config:
    cpu_count: 1
    use_shared_threads: true

  self_management_config:
    enabled: true

  host_configs:
    - host_config_id: 1
      drive:
        - path: SectorMap:1:64

  hosts:
    - host: localhost
      port: 19001
      host_config_id: 1
      location:
        data_center: dc-a

    - host: localhost
      port: 19002
      host_config_id: 1
      location:
        data_center: dc-b
