metadata:
  kind: MainConfig
  cluster: ydb-mirror-3-dc-3-nodes-bridge
  version: 0
config:
  erasure: mirror-3-dc
  fail_domain_type: disk
  default_disk_type: SSD
  yaml_config_enabled: true
  actor_system_config:
    cpu_count: 1
    use_shared_threads: true
  self_management_config:
    enabled: true
  bridge_config:
    piles:
      - name: dc-a
      - name: dc-b
  domains_config:
    domain:
      - domain_id: 1
        name: Root
  host_configs:
    - host_config_id: 1
      drive:
        - path: SectorMap:1:64
          type: SSD
        - path: SectorMap:2:64
          type: SSD
        - path: SectorMap:3:64
          type: SSD

  hosts:
    - host: localhost
      port: 19001
      host_config_id: 1
      bridge_pile_name: dc-a
      location:
        data_center: dc-a

    - host: localhost
      port: 19002
      host_config_id: 1
      bridge_pile_name: dc-a
      location:
        data_center: dc-a

    - host: localhost
      port: 19003
      host_config_id: 1
      bridge_pile_name: dc-a
      location:
        data_center: dc-a

    - host: localhost
      port: 19004
      host_config_id: 1
      bridge_pile_name: dc-b
      location:
        data_center: dc-b

    - host: localhost
      port: 19005
      host_config_id: 1
      bridge_pile_name: dc-b
      location:
        data_center: dc-b

    - host: localhost
      port: 19006
      host_config_id: 1
      bridge_pile_name: dc-b
      location:
        data_center: dc-b
