metadata:
  kind: MainConfig
  cluster: ydb-cluster
  version: 0
config:
  erasure: none
  fail_domain_type: disk
  default_disk_type: SSD
  yaml_config_enabled: true
  actor_system_config:
    cpu_count: 2
    use_shared_threads: true
  self_management_config:
    enabled: true
  bridge_config:
    piles:
      - name: pile-1
      - name: pile-2
  host_configs:
    - host_config_id: 1
      drive:
        - path: SectorMap:1:64
          type: SSD

  hosts:
    - host: localhost
      port: 19001
      host_config_id: 1
      bridge_pile_name: pile-1
      location:
        data_center: dc-a

    - host: localhost
      port: 19002
      host_config_id: 1
      bridge_pile_name: pile-2
      location:
        data_center: dc-b
