receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheusremotewrite:
    endpoint: 0.0.0.0:9091
  prometheus/ydb-nodes:
    config:
      scrape_configs:
        - job_name: ydb-storage-nodes
          scrape_interval: 10s
          metrics_path: /counters/prometheus
          static_configs:
            - targets:
                - localhost:8765
        - job_name: ydb-database-nodes
          scrape_interval: 10s
          metrics_path: /counters/prometheus
          static_configs:
            - targets:
                - localhost:8766
                - localhost:8767
                - localhost:8768

exporters:
  prometheus:
    endpoint: 0.0.0.0:9090
  file/metrics:
    path: /data/metrics.jsonl

service:
  telemetry:
    logs:
      level: info
  pipelines:
    metrics:
      receivers: [otlp, prometheusremotewrite, prometheus/ydb-nodes]
      exporters: [prometheus, file/metrics]
