global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ydb-storage-nodes
    scrape_interval: 10s
    metrics_path: /counters/prometheus
    static_configs:
      - targets:
          - ydb-storage-1:8765

  - job_name: ydb-database-nodes
    scrape_interval: 10s
    metrics_path: /counters/prometheus
    static_configs:
      - targets:
          - ydb-database-1:8765
          - ydb-database-2:8765
          - ydb-database-3:8765
