global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ydb-storage-nodes
    scrape_interval: 10s
    metrics_path: /counters/prometheus
    static_configs:
      - targets:
          - localhost:8765

  - job_name: ydb-database-nodes
    scrape_interval: 10s
    metrics_path: /counters/prometheus
    static_configs:
      - targets:
          - localhost:8766
          - localhost:8767
          - localhost:8768
