global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ydb
    scrape_interval: 5s
    metrics_path: /counters/counters=ydb/name_label=name/prometheus
    static_configs:
      - targets:
          - ydb-database-1:8765
          - ydb-database-2:8765
          - ydb-database-3:8765
          - ydb-database-4:8765
          - ydb-database-5:8765

  - job_name: interconnect
    scrape_interval: 5s
    metrics_path: /counters/counters=interconnect/prometheus
    static_configs:
      - targets:
          - ydb-database-1:8765
          - ydb-database-2:8765
          - ydb-database-3:8765
          - ydb-database-4:8765
          - ydb-database-5:8765
